name: Check
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
jobs:
  nvm:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      NVMRC: ${{ steps.nvm.outputs.NVMRC }}
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: |
          echo ::set-output name=NVMRC::$(cat .nvmrc)
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: nvm
    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.nvm.outputs.NVMRC }}
      - id: yarn-cache-dir
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run cloud:ci
      - run: |
          yarn run lint
      - run: |
          yarn run affected:test
      - run: |
          yarn run build:design
      - run: |
          yarn run chromatic
      - uses: chromaui/action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: dist/apps/design
      - if: always()
        run: |
          yarn run cloud:stop
      - if: github.event_name != 'pull_request'
        uses: nrwl/nx-tag-successful-ci-run@v1
      - if: always()
        uses: codecov/codecov-action@v2
        with:
          directory: coverage
      - if: failure()
        run: |
          yarn run fix
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
  agents:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: nvm
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.nvm.outputs.NVMRC }}
      - id: yarn-cache-dir
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn cypress install
      - run: |
          yarn run cloud:start
